from gym.envs.classic_control.cartpole import CartPoleEnv
from gym.envs.classic_control.mountain_car import MountainCarEnv
from gym.envs.classic_control.continuous_mountain_car import Continuous_MountainCarEnv
from gym.envs.classic_control.pendulum import PendulumEnv
from gym.envs.classic_control.acrobot import AcrobotEnv
from gym.envs.classic_control.pendulum_new import Pendulum2Env
from gym.envs.classic_control.pendulum_new import Pendulum3Env
from gym.envs.classic_control.pendulum_new import Pendulum1Env
from gym.envs.classic_control.cartpole_2 import CartPoleEnv2
from gym.envs.classic_control.airplane import AirplaneEnv
